// <auto-generated />
using System;
using ApparelMiddlewareGateway.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApparelMiddlewareGateway.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909172624_AddCuttingJobsAndRolls")]
    partial class AddCuttingJobsAndRolls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApparelMiddlewareGateway.Models.CuttingJob", b =>
                {
                    b.Property<string>("CuttingJobNo")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TargetLine")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("CuttingJobNo");

                    b.ToTable("CuttingJobs");

                    b.HasData(
                        new
                        {
                            CuttingJobNo = "JOB-1001",
                            Status = "Active",
                            TargetLine = "Spreader_01"
                        },
                        new
                        {
                            CuttingJobNo = "JOB-1002",
                            Status = "Active",
                            TargetLine = "Spreader_02"
                        });
                });

            modelBuilder.Entity("ApparelMiddlewareGateway.Models.Roll", b =>
                {
                    b.Property<string>("CuttingJobNo")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RollID")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("CuttingJobNo", "RollID");

                    b.ToTable("Rolls");

                    b.HasData(
                        new
                        {
                            CuttingJobNo = "JOB-1001",
                            RollID = "R-1045",
                            Status = "Pending"
                        },
                        new
                        {
                            CuttingJobNo = "JOB-1001",
                            RollID = "R-1046",
                            Status = "Pending"
                        },
                        new
                        {
                            CuttingJobNo = "JOB-1001",
                            RollID = "R-1047",
                            Status = "Pending"
                        },
                        new
                        {
                            CuttingJobNo = "JOB-1002",
                            RollID = "R-2050",
                            Status = "Pending"
                        },
                        new
                        {
                            CuttingJobNo = "JOB-1002",
                            RollID = "R-2051",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("ApparelMiddlewareGateway.Models.SpreaderTelemetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualPlyHeight")
                        .HasColumnType("int");

                    b.Property<string>("CuttingJobNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("Damage")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("EndBit")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal>("OverlapEnd")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("OverlapStart")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RollID")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CuttingJobNo", "RollID")
                        .IsUnique();

                    b.ToTable("SpreaderTelemetryRecords");
                });

            modelBuilder.Entity("ApparelMiddlewareGateway.Models.Roll", b =>
                {
                    b.HasOne("ApparelMiddlewareGateway.Models.CuttingJob", "CuttingJob")
                        .WithMany("Rolls")
                        .HasForeignKey("CuttingJobNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuttingJob");
                });

            modelBuilder.Entity("ApparelMiddlewareGateway.Models.CuttingJob", b =>
                {
                    b.Navigation("Rolls");
                });
#pragma warning restore 612, 618
        }
    }
}
